### ISSUE TITLE
tomtomMap.getUserLocation() always return null

### ISSUE THREAD

**Issue by TobinFrost** [tomtom-international/maps-sdk-for-android-examples#1]
Hi ! I was practicing the tutorial https://developer.tomtom.com/maps-sdk-android/android-tutorials-use-cases/search-along-route and i get errors when i'm trying to get user location and **tomtomMap.centerOnMyLocation()** do not work anymore.

**Comment by mwlodarczyk** [comment]
Hi @TobinFrost,

Do you have my location enabled? To enable location tracking, use the following code:

```
@Override
    public void onMapReady(TomtomMap tomtomMap) {
        //Map is ready here
        tomtomMap.setMyLocationEnabled(true);
}
```

Additionally, you need to forward permissions callbacks from Activity to TomtomMap:

```
@Override
public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
    super.onRequestPermissionsResult(requestCode, permissions, grantResults);
    tomtomMap.onRequestPermissionsResult(requestCode, permissions, grantResults);
}
```
