### ISSUE TITLE
GPS Indicator enlarged size, cannot change size or fix

### ISSUE THREAD

**Issue by rashid4lyf** [tomtom-international/maps-sdk-for-android-examples#15]
In the latest version, 2.4.617 the gps indicator is huge, across multiple devices (S6, S8, Oneplus 7, 7T & 8). Possibly other devices too. This issue is not present on 2.4.602 (previous build my app was built on).

The issue is also present and can be replicated on the sample app (JAVA) if you select a custom map style.

**Comment by kjdalglish** [comment]
Same issue here.

**Comment by Flyentology** [comment]
Hey, 

Sorry for late reply. Could you try version 2.4.637? The issue with GPS Indicator should be resolved.

**Comment by rashid4lyf** [comment]
> Hey,
> 
> Sorry for late reply. Could you try version 2.4.637? The issue with GPS Indicator should be resolved.

Hi,

This issue has been fixed but this version seems to contain a massive memory leak on the native code side which makes this release not usuable. Memory leak seems to get bigger as I conduct routing queries.
