### ISSUE TITLE
Memory Leak on MapFragment 

### ISSUE THREAD

**Issue by rashid4lyf** [tomtom-international/maps-sdk-for-android-examples#16]
I have an app which uses a mapFragment within a fragment. I am using the jetpack navigation tools and when moving between the main map fragment to another fragment and back again the RAM increases considerably. 

This can be seen on profiling section with native code taking over 1GB. 

If I do not move between fragments the RAM is stable.

**Comment by Flyentology** [comment]
Hi,

Could you provide more information & reproduction steps for this issue?

It would be super helpful if you could either create a simple project where issue occurs or reproduce it in our sample application.

**Comment by rashid4lyf** [comment]
Hi,

So if you have a base android project with a MainActivity and a map on fragment 1. Then if you use the navigation drawer to move between fragment 1 and fragment 2 and back to fragment 1 you will notice an increase in RAM. This balloons up more and more if you do this repeatedly. When the java garbage collector is called and previous instances of that fragment is destroyed the native C code ram usage does not go down. This can be seen via the profiler section on android studio and was replicated using a OnePlus 7T Pro running Android 10. 

I think the cause is because the fragment is recreated which causes a new map instance to be created.

**Comment by Flyentology** [comment]
Hello,

Issue got reported to the team. I will reply in this thread when we finish our investigation on this problem.

**Comment by gary0707** [comment]
Hi, 

in the very first comment @rashid4lyf wrote:
`I have an app which uses a mapFragment within a fragment`

Did you mean nested fragments scenario or maybe "an app which uses MapView within a Fragment" ?

**Comment by rashid4lyf** [comment]
> Hi,
> 
> in the very first comment @rashid4lyf wrote:
> `I have an app which uses a mapFragment within a fragment`
> 
> Did you mean nested fragments scenario or maybe "an app which uses MapView within a Fragment" ?

Nested fragment scenario, so I am using the android Jetpack navigation framework and inside fragment1 I have a fragmentContainerView that initialises the mapFragment. 

So layout file would look like:

- ConstraintView (root)
   + FragmentContainerView 
   + LinearLayout 
       + ....

**Comment by gary0707** [comment]
I have created an app based on your description, but I cannot observe the aforementioned memory leak. 
I navigate between fragments multiple times, but the native memory does not grow. I also use nested `MapFragment`, Navigation Drawer and Jetpack's Navigation.

Would it be possible to share the code with us or at least logs from our SDK?
In order to enable logs please use the `LogUtils` available in the Maps SDK. 
Sample usage in the app `onCreate()`:
```java
@Override
public void onCreate() {
    super.onCreate();
    LogUtils.enableLogs(Log.VERBOSE);
    ...
}
```

**Comment by rashid4lyf** [comment]
I can share the code. I will create a basic app with the above mentioned scenario and will also enable  logs again. This should be done within the next 24 hours.

**Comment by gary0707** [comment]
Hi @rashid4lyf,
is the issue you have raised still valid? Did you have a chance to create the basic app you have mentioned about?

**Comment by rashid4lyf** [comment]
Hi, apologies for the delay. I have created the app and added it as a zip file to this comment. I have also added an image showing how the memory allocated to native code increases over time. It also seems to increase more heavily when clicking the location button on the map. 

[DemoTestApplication.zip](https://github.com/tomtom-international/maps-sdk-for-android-examples/files/5322882/DemoTestApplication.zip)
![native_memory_increase](https://user-images.githubusercontent.com/69960896/95011220-07d7b380-0627-11eb-8bf0-b3670b551b8d.png)

**Comment by rashid4lyf** [comment]
Hi @gary0707 I was wondering if there was an update on this  and whether there is a workaround? 😊

**Comment by lukasztokarski-tomtom** [comment]
Hi, sorry for the late response. 
Thank you for the provided source code. We have identified the root cause of the problem. The fix for that should be delivered with the next release of the Maps SDK for Android. Thank you for spotting the problem!

**Comment by rashid4lyf** [comment]
@lukasztokarski-tomtom thank you for the update! Glad I could assist.

**Comment by rashid4lyf** [comment]
Hello, 

I can confirm this issue has been fixed in the new release and working much better :)

**Comment by lukasztokarski-tomtom** [comment]
Thank you for the feedback. We are happy that it works correctly!
