### ISSUE TITLE
java.lang.IllegalStateException: Coordinates are out of bounds. in new SDK 2.4.674

### ISSUE THREAD

**Issue by rashid4lyf** [tomtom-international/maps-sdk-for-android-examples#18]
Hi, the new maps SDK 2.4.674 has an issue:

Error: `java.lang.IllegalStateException: Coordinates are out of bounds.`

How to reproduce: 
 
- When the map is fully zoomed out, scroll from one end of the world to the other quickly and the crash will occur. If scrolling slower, the crash does not happen.

`com.tomtom.online.sdk.common.location.LatLng.a LatLng.java:145
com.tomtom.online.sdk.common.location.LatLng.<init> LatLng.java:64
com.tomtom.core.maps.NativeMapViewImpl.nativeGetLatLng NativeMapViewImpl.java
com.tomtom.core.maps.NativeMapViewImpl.getLatLng NativeMapViewImpl.java:355
com.tomtom.online.sdk.map.aq.getMapFocalPoint MapViewNativeController.java:275
com.tomtom.online.sdk.map.be.getCenterOfMap TomtomMapImpl.java:218
com.tomtom.online.sdk.map.bk.onMapViewPortChanged UiComponentsController.java:147
com.tomtom.online.sdk.map.camera.CameraListenersContainer$b.a CameraListenersContainer.kt:72
com.tomtom.online.sdk.common.func.FuncUtils.forEach FuncUtils.java:51
com.tomtom.online.sdk.common.callbacks.ListCallbackContainer.doOnEachCallback ListCallbackContainer.java:62
com.tomtom.online.sdk.map.camera.CameraListenersContainer.a CameraListenersContainer.kt:71
com.tomtom.online.sdk.common.func.FuncUtils.forEach FuncUtils.java:51
com.tomtom.online.sdk.common.callbacks.ListCallbackContainer.doOnEachCallback ListCallbackContainer.java:62
com.tomtom.online.sdk.map.camera.application.CameraEventsPublisher.publish CameraEventsPublisher.kt:36`

**Comment by mkaczmarek93** [comment]
Hi,
Thanks for reporting this issue. 
I will reply in this thread when we finish our investigation on this problem.

**Comment by rashid4lyf** [comment]
Hi, Is there any update on this? @mkaczmarek93 :)

**Comment by mkaczmarek93** [comment]
HI, the fix should be delivered with the next release of the Maps SDK for Android.

**Comment by mkaczmarek93** [comment]
Hi @rashid4lyf ,

The issues was fixed in [2.4.712](https://github.com/tomtom-international/maps-sdk-for-android-examples/releases/tag/2.4.712).
Can you confirm?

**Comment by rashid4lyf** [comment]
Apologies for the delay in response. I can confirm this bug has been resolved :) thank you
