### ISSUE TITLE
Marker not visible When adding marker on Map

### ISSUE THREAD

**Issue by TobinFrost** [tomtom-international/maps-sdk-for-android-examples#3]
Hi ! Guys
I really need help.
i'm using fragment in a FragmentLayout to display the map and evry thing is fine. 
The problem is cant see the markers i've created.

Here is my code 

```
public void onMapReady(@NonNull TomtomMap tomtomMap) {
        this.tomtomMap = tomtomMap;
        tomtomMap.setMyLocationEnabled(true);
        LatLng position = new LatLng(14.689876, -17.454631);

        Icon i = Icon.Factory.fromResources(getContext(), R.drawable.ic_favourites);
        SimpleMarkerBalloon balloon = new SimpleMarkerBalloon("Here we are");
        Marker m = this.tomtomMap.addMarker(new MarkerBuilder(position).markerBalloon(balloon).icon(i));
        tomtomMap.centerOn(CameraPosition.builder(position).zoom(15).build());
        Log.e("Tomtom Marker","Marker Icon Height -> "+m.getIconHeight());
        Log.e("Tomtom Marker","Marker Icon Width -> "+m.getIconWidth());
        Log.e("Tomtom Marker","Marker Icon  Position-> "+m.getPosition().toString());
        Log.e("Tomtom Marker","Is Marker Active -> "+this.tomtomMap.getMarkerSettings().areMarkersActive());


        showProgress(false);
    }
```

`<fragment
        android:id="@+id/mapFragment"
        android:name="com.tomtom.online.sdk.map.MapFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />`

**Comment by mariopce** [comment]
Hi I used your code and I copied into our sampleapp to `FunctionalExamplesActivity.java` and code works. 
I'm attaching diff and screenshot. 
Do you have more logs, please use latest version 2.404 end enable more logs in your app: 
https://developer.tomtom.com/maps-android-sdk/map-initialization ( log level section) 

[markerInSampleApp.diff.txt](https://github.com/tomtom-international/maps-sdk-for-android-examples/files/2680280/markerInSampleApp.diff.txt)
![2770118359665547051](https://user-images.githubusercontent.com/629491/50007001-cc7e7780-ffaf-11e8-92a1-a5b4c167119a.jpg)

**Comment by TobinFrost** [comment]
You do not think the problem is caused by the layout.
I'm using a FragmentLayout and Context is a Fragment instead of an Activity.
I have the same image as you but without the Marker.

**Comment by TobinFrost** [comment]
My Fault !!!
I used 
`mapFragment = (MapFragment) getActivity().getSupportFragmentManager().findFragmentById(R.id.mapFragment);
`
instead of 
`mapFragment = (MapFragment) getChildFragmentManager().findFragmentById(R.id.mapFragment);`

Thank u !!

**Comment by mariopce** [comment]
Thank you for sharing the solution.
Best Regards Mariusz.
