### ISSUE TITLE
Proguard

### ISSUE THREAD

**Issue by JoniDS** [tomtom-international/maps-sdk-for-android-examples#5]
Using **implementation("com.tomtom.online:sdk-maps:2.438")** it adds **50MB** to the final APK.
Checking the dependencies, it brings in a lot of them (namely google play services):

![Screenshot 2019-04-16 at 12 29 13](https://user-images.githubusercontent.com/1437129/56202580-acd18b80-6043-11e9-8320-2679ca1ae4e2.png)

Is there any way to trim down the dependencies/size of the final apk (or Proguard definitions)?

Thanks

**Comment by mariopce** [comment]
the better option is using android app bandle feature. 
You just need call 
`./gradlew bundle` to generate abb file. 
Upload that file to google play console like a normal apk and Google manage to decrease the size to around 10MB

**Comment by JoniDS** [comment]
> the better option is using android app bandle feature.
> You just need call
> `./gradlew bundle` to generate abb file.
> Upload that file to google play console like a normal apk and Google manage to decrease the size to around 10MB

That's fair, but looking at the dependency tree, we can see **com.tomtom.online:sdk-location** is the one bringing most of the dependencies.
Why does **com.tomtom.online:sdk-maps** depend on **com.tomtom.online:sdk-location**, and can't it be made an optional dependency?

This (com.tomtom.online:sdk-location) forces us to import Google Play Services even if we just want to use the "Maps" component.

**Comment by rsulkowski** [comment]
It is true that there are some size issues of the SDK. We have several improvements to planned on our backlog. One of them is to cleanup dependencies. Apart from proposed solution you can also take a look into the possibility to host style on remote server and follow instructions from this section to set custom url of the style: https://developer.tomtom.com/maps-sdk-android/custom-style . It should also influence the final apk size.

**Comment by mariopce** [comment]
you're right, but this is just a simple configuration. For developers who want quick setup the map for common thinks. 
If you would like to use just the map, exclude the sdk-location from map dependencies. 
```
implementation("com.tomtom.online:sdk-maps:2.4042") {
    exclude group: 'com.tomtom.online', module: 'sdk-location'
} 
```

**Comment by JoniDS** [comment]
That works, but only if we manually add a dependency on **Play Service Location** because **maps/common** has a hard-coded reference to Google Play services.

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.tomtom.online.sdk.map"
    android:versionCode="2438"
    android:versionName="2.1.2438" >

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="26" />

    <uses-feature android:glEsVersion="0x00020000" />

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

    <application>
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
    </application>

</manifest>
```

`AAPT: error: resource integer/google_play_services_version (aka com.mapstest:integer/google_play_services_version) not found.`


And yes

**Comment by mwlodarczyk** [comment]
As discussed, the above mentioned improvements are planned for the future. For now, mentioned workarounds should be used. We will notify once ready through the release notes.
