### ISSUE TITLE
AGPBI: {"kind":"error","text":"error: resource android:attr/ttcIndex not found.","sources

### ISSUE THREAD

**Issue by Ryanke** [tomtom-international/maps-sdk-for-android-examples#6]
AGPBI: {"kind":"error","text":"error: resource android:attr/ttcIndex not found.","sources":[{"file":"/Users/kerui/.gradle/caches/transforms-1/files-1.1/sdk-common-2.4055.aar/3f2b03e011edcbab394f351280290a4a/res/values/values.xml","position":{"startLine":4,"startColumn":4,"startOffset":185,"endColumn":47,"endOffset":228}}],"original":"","tool":"AAPT"}
:app:processBuildTestDebugResources
:app:processBuildTestDebugResources FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processBuildTestDebugResources'.
> Failed to process resources, see aapt output above for details.

**Comment by mariopce** [comment]
`app:processBuildTestDebugResources`
Looks like the issue is not related with the SDK- we don't provide tests for the SDK. 
Please make sure that U use latest build tools.
