### ISSUE TITLE
AndroidManifest merge error using FileProvider

### ISSUE THREAD

**Issue by paopao-yu** [tomtom-international/maps-sdk-for-android-examples#8]
When I integrated the tomtom
implementation 'com.tomtom.online:sdk-maps:2.4101'
implementation 'com.tomtom.online:sdk-search:2.4101'

I got the error 
Attribute provider#android.support.v4.content.FileProvider@authorities value=(com.my.fileprovider) from [:UtilsModule:UtilsModuleLib] AndroidManifest.xml:18:13-69
	is also present at [com.tomtom.online:sdk-common:2.4101] AndroidManifest.xml:17:13-60 value=(com.my.provider).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:16:9-24:20 to override.

**Comment by paopao-yu** [comment]
I used this answer (https://stackoverflow.com/a/42989182/2749143) to fix. 
But I thought third party libraries to fix this problem will be better.

**Comment by mwlodarczyk** [comment]
Hi @paopao-yu,

Thanks for your feedback. We will have a look into this so that the fix can be made on the SDK level.

Best,
Michal
