### ISSUE TITLE
tomtomMap.getUserLocation() return null

### ISSUE THREAD

**Issue by Michlithr** [tomtom-international/maps-sdk-for-android-examples#9]
Hi, i see that there is this topic from 2018 but answear didnt resolve my problem. 
1) I have already granted permission with :
```
@Override
    public void onRequestPermissionsResult(int requestCode,
                                           @NotNull String[] permissions,
                                           @NotNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);

        tomtomMap.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }`
```
2) In on map ready im setting myLocation to enabled : `
        tomtomMap.setMyLocationEnabled(true);`
3) and finally im trying to make this working 
`   tomtomMap.centerOnMyLocation();
    tomtomMap.getUserLocation();`
So whats the problem with this methods? Why current location is allways null and center doesn't work? All what i can find is that getUserLocation returns null if i dont have permissions, but im granting permission and im enabling myLocation...

**Comment by mwlodarczyk** [comment]
There might be several issues:

- Location permissions are not granted
- Location permissions are not properly passed to the TomtomMap object
- Location is not obtained. Until the location is obtained, this method may return null

Can you see the blue dot on the map? This icon indicates user position.

**Comment by Michlithr** [comment]
Yes, the problem is that i see this dot which is on my current location. Also I can use default Tomtom button which centers map on my location - even if i can do that and i see my location on map i can't gent my cords programmatically.

**Comment by Nielska** [comment]
Is this solved already, I'm encountering the exact same problem

**Comment by MichalWlodarczyk2TomTom** [comment]
Closing the issue, it seems to be fixed with the latest version.
